/**
 * Zero-dependency bundle builder: wraps the src modules into the
 * __ModuleLoader__ factory format the DSH client expects and writes
 * client/client.js. Each src module becomes an IIFE with `mod`/`exports`
 * as its local surface; siblings are reached through the `local` object,
 * externals (react) through the factory's `require`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Dependency-ordered roster; entry must stay last.
const MODULES = ['styles', 'locales', 'store', 'state', 'dock', 'settings-panel', 'entry']

const lines = []
lines.push('// GENERATED by scripts/build.mjs — do not edit directly.')
lines.push(`window.__ModuleLoader__.load({ id: 'ds-whale-ui', factory: (require) => {`)
lines.push('  const module = { exports: {} }')
lines.push('  const exports = module.exports')
lines.push(`  Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })`)
lines.push('  const local = {}')
for (const name of MODULES) {
  const src = readFileSync(join(root, 'src', `${name}.js`), 'utf8')
  lines.push(`  local[${JSON.stringify(name)}] = (() => { const mod = {}; const exports = mod;`)
  lines.push(src)
  lines.push('  return mod })()')
}
lines.push(`  const entry = local['entry']`)
lines.push('  exports.name = entry.name')
lines.push('  exports.inject = entry.inject')
lines.push('  exports.apply = entry.apply')
lines.push('  return module.exports')
lines.push('}})')
lines.push('')

mkdirSync(join(root, 'client'), { recursive: true })
writeFileSync(join(root, 'client', 'client.js'), lines.join('\n'))
console.log('built client/client.js')
